spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=NovaScheduled;encrypt=true;trustServerCertificate=true;
    username: sa
    password: StrongPassword123!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update # İsteğe göre: validate, update, create, create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect

  datasource.hikari:
    maximum-pool-size: 10
    minimum-idle: 5
    idle-timeout: 30000
    connection-timeout: 30000